name: Scan
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install pipenv 
          make install
      - name: Get the current version
        run: |
          echo "VERSION=$(pipenv run semantic-release print-version --current)"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Current version is $VERSION"
      - name: Print the current version
        run: echo "Current version is $VERSION"
      - name: Build an image from Dockerfile
        run: |
          docker build \
            --build-arg VERSION=$(pipenv run semantic-release print-version --current) \
            -t tvallas/mtr2mqtt:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'tvallas/mtr2mqtt:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'